### ISSUE TITLE
Step by step manual 

### ISSUE THREAD

**Issue by bsurai** [nodebeats/nodebeats#10]
Hey.
Is there any step by step manual to get creating a simple site.
I'm asking because I always see `/admin` page, even after pressing `Visit site` link.

**Comment by nodebeats** [comment]
@bsurai you can uncomment the path: ' ' route inside nodebeats/admin/src/app/app.route.ts file and comment the redirectTo: 'admin' line and then run your project .. It wont redirect to admin page initially..
Then, you can start creating your website inside home-app folder.

And, we are sorry that we removed the documentation for this release. We are working on upgrading the project to implement server side rendering and we will be releasing it very soon(may be 1 or 2 weeks from now) with full documentation. The next release is going to be huge. So, stay updated and share with your friends as well. 
Please join our channels, where you can message us with your query and contribute to the project by sharing your experience and ideas regarding the project.
Telegram: https://t.me/nodebeats 
Gitter: https://gitter.im/nodebeats/nodebeats
