### ISSUE TITLE
Issues when setup on localhost

### ISSUE THREAD

**Issue by chandanchhajer** [nodebeats/nodebeats#11]
Hello, I'm facing some issues when I setup this cms on my localhost server. Here these are:
1. An alert ("Google analytics configuration File not found") is displaying on dashboard.
2. An alert ("Email service configuration not found") is displaying when adding user.
3. An alert ("Internal server error") is displaying when adding user role.
Can you please provide any solution for these issues ?
Also, I want to customise this cms according to my requirements, Can you please provide any guideline for cms modules structure and about coding flow ?

**Comment by avsek477** [comment]
You can check the DOCS and API DOCS on our website. https://www.nodebeats.com/
