### ISSUE TITLE
Credentials Incorrect

### ISSUE THREAD

**Issue by sistemasyapps** [nodebeats/nodebeats#14]
the credentials are Incorrect to login I try with 
/*----------superadmin login-------*/
superadmin
testsuperadmin

![image](https://user-images.githubusercontent.com/32423610/42737408-dd534144-8840-11e8-97d7-471eeb2c21d7.png)

**Comment by avsek477** [comment]
The password for login is: testpassword123

**Comment by ghost** [comment]
I can't login with username: `superadmin` and password: `testpassword123`

**Comment by chandanchhajer** [comment]
Finally I findout the login credentails here in file: /lib/configs/application.config.js
**Username: superadmin
Password: superadmin@123**

**Comment by pooja1425** [comment]
I tried with the password mentioned in application.config.js file... bt still not able to login.. it shows invalid credentials..

**Comment by gapcytech** [comment]
> I tried with the password mentioned in application.config.js file... bt still not able to login.. it shows invalid credentials..

Make sure you are integrating correct DB... I hope that will be on your localhost.
There is a collection "user" in mongodb databse with a admin user entry as shown below

{
    "_id" : ObjectId("58497c16072f6c20f4fac319"),
    "addedBy" : "system",
    "userRole" : "superadmin",
    "securityAnswerSalt" : "$2a$12$2d3OMt1DY6KUifrKG4dMAO",
    "securityAnswer" : "$2a$12$2d3OMt1DY6KUifrKG4dMAOirFKT3mlKT3p0YhVZQFKNOp6QDjcxdi",
    "securityQuestion" : "Who was your childhood hero ?",
    "passwordSalt" : "$2a$12$8VyM4927V0pg3d4/qfxNGe",
    "password" : "$2a$12$8VyM4927V0pg3d4/qfxNGeUqMi10uZEuj6KCB/5qUtvjZpwcLjp1.",
    "username" : "superadmin",
    "blockedOn" : ISODate("2018-07-27T16:35:21.726Z")
}

update your admin data in DB with these data so may be you can login successfully. Update password and salt strings.

**Comment by chandanchhajer** [comment]
> I tried with the password mentioned in application.config.js file... bt still not able to login.. it shows invalid credentials..

Make sure you are integrating correct DB... I hope that will be on your localhost.
There is a collection "user" in mongodb databse with a admin user entry as shown below

```
{
"_id" : ObjectId("58497c16072f6c20f4fac319"),
"addedBy" : "system",
"userRole" : "superadmin",
"securityAnswerSalt" : "$2a$12$2d3OMt1DY6KUifrKG4dMAO",
"securityAnswer" : "$2a$12$2d3OMt1DY6KUifrKG4dMAOirFKT3mlKT3p0YhVZQFKNOp6QDjcxdi",
"securityQuestion" : "Who was your childhood hero ?",
"passwordSalt" : "$2a$12$8VyM4927V0pg3d4/qfxNGe",
"password" : "$2a$12$8VyM4927V0pg3d4/qfxNGeUqMi10uZEuj6KCB/5qUtvjZpwcLjp1.",
"username" : "superadmin",
"blockedOn" : ISODate("2018-07-27T16:35:21.726Z")
}
```
update your admin data in DB with these data so may be you can login successfully. Update password and salt strings.
