### ISSUE TITLE
The site seems non responsive in netbook or tab screen sizes

### ISSUE THREAD

**Issue by animeshsinghweb** [nodebeats/nodebeats#3]
The main site http://www.nodebeats.com seems non-responsive in small screen devices like a low-resolution netbook.

Here are few screenshot, that better illustrate the issue:
![image](https://cloud.githubusercontent.com/assets/16618931/23870833/eab3b68a-084d-11e7-9e6d-4f0ecf22f66a.png)

![image](https://cloud.githubusercontent.com/assets/16618931/23870904/2c486d66-084e-11e7-9e6c-bfdb1ea20b6e.png)

![image](https://cloud.githubusercontent.com/assets/16618931/23870928/50bf289c-084e-11e7-9c49-4236ac653662.png)

Device used: HP Mini 210
Default Resolution of the device: 1024 x 600

**Comment by ShrawanLakhe** [comment]
Thank you very much @animeshsinghweb . Soon we will introduce mobile ready design with nodebeats.com and also with nodebeats cms.

**Comment by felipealfonsog** [comment]
yeah it's part of the challenges we have ahead ... :+1:

**Comment by felipealfonsog** [comment]
Always , if it's not always, in the CSS file ... or code. .. of CSS .... check it that out carefully ... sometimes it's easy to miss something out ... :+1:

**Comment by ShrawanLakhe** [comment]
Yeah it is easy to miss something. Appreciate your feedback. We will continue to improve this cms and we will need your continued feedback and suggestions

**Comment by nodebeats** [comment]
Please check out our new nodebeats release. The website is full responsive. 

https://www.nodebeats.com/
