### ISSUE TITLE
Redis connection lost

### ISSUE THREAD

**Issue by roushanj** [nodebeats/nodebeats#6]
![screenshot from 2017-06-12 12-24-33](https://user-images.githubusercontent.com/12628507/27022193-7eb4aafc-4f6a-11e7-990c-3e1488bb585c.png)

I have created database
and also configured redis and still i am finding this error could you please help me out here

**Comment by ShrawanLakhe** [comment]
hi roshan have you configured the redis server correct credentials for  redis.config.js  file inside of lib/configs directory.  If yes and still you are getting error, then , you can uncomment the line having this text  in app.js at the root of the project 
`store: new RedisStore(redisStoreOpts),`

and then run the application again.

**Comment by roushanj** [comment]
Ok I will it and let you know
Thank you
