### ISSUE TITLE
Hey hi... im getting this error after command :- npm run build

### ISSUE THREAD

**Issue by VikashchNishad** [nodebeats/nodebeats#7]
Hey hi im getting error after running this command :- npm run build.

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/core relative to /home/vikash/node_modules/@angular/cdk/typings/index.d.ts., resolving symbol A11yModule in /home/vikash/node_modules/@angular/cdk/typings/index.d.ts, resolving symbol A11yModule in /home/vikash/node_modules/@angular/cdk/typings/index.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/vikash/Angular-2/nodebeats-master/admin/src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts

**Comment by ShrawanLakhe** [comment]
Hi @VikashchNishad  We are really sorry for the late reply and we will soon come with the new release of nodebeats., As for now it has some issues on angular side. 
Thank you

**Comment by avsek477** [comment]
The new release is ready for production build.
